### ISSUE TITLE
Permission error; help needed with installation

### ISSUE THREAD

**Issue by Ronaldho80** [bibbox/app-seeddms#3]
First, I did not know how to use this repository. After a while, I thought, I just need to edit the docker-compose.yml file and make it run. So, I edited it like this:

```
version: '2'

networks:
    bibbox-default-network:
      external: true
      
services:

  seeddms:
    image: bibbox/seeddms
    container_name:  seeddms
    restart: unless-stopped
    networks:
      - bibbox-default-network
    links:
      - seeddms-db:seeddms-db
    ports:
      - "8888:80"
    depends_on:
      - seeddms-db
      - seeddms-data
    volumes_from: 
      - seeddms-data

  seeddms-db:
    image: mysql:5
    container_name: seeddms-db
    restart: unless-stopped
    networks:
      - bibbox-default-network
    user: root
    environment:
      - MYSQL_ROOT_PASSWORD=audi007
      - MYSQL_DATABASE=seeddms
      - MYSQL_USER=seeddms
      - MYSQL_PASSWORD=audi007
    volumes_from: 
      - seeddms-data
    depends_on:
      - seeddms-data

  seeddms-data:
    image: busybox
    container_name: seeddms-data
    volumes:
      - ./var/lib/mysql:/var/lib/mysql
      - ./var/www/seeddms51x/data:/var/www/seeddms51x/data

```

- Then, I run `docker-compose up` and it told me to add the bibbox network manually.
- I did this and again run `docker-compose up`.
- I opened `http://hans:8888/install` and the installation screen opened.
- I entered my chosen password: `audi007` in the "Password:" text field 
- I clicked on "Create database tables" 
- I clicked on `Apply`
Now, I got this error messages:
![image](https://user-images.githubusercontent.com/14110695/40833968-ad5d3888-658f-11e8-90cb-acda779d454c.png)

Could you pls help me with the installation?

Thx a lot and best regards,
Ronny
